name: my_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Media
  image_picker: ^1.0.4
  camera: ^0.10.5+9
  video_player: ^2.8.1

  # State management
  provider: ^6.1.1

  # UI / Animations
  js: ^0.7.2
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.0.0
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/animations/camera.json
    - assets/animations/map.json
    - assets/animations/splash.json
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/back.png
  
