// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcQXZpw7NqHhmXzYPuZdfjKoad44gJW0',
    appId: '1:649861279221:web:4bcb7479a0785bf66f04bc',
    messagingSenderId: '649861279221',
    projectId: 'report-app-ccc12',
    authDomain: 'report-app-ccc12.firebaseapp.com',
    storageBucket: 'report-app-ccc12.firebasestorage.app',
    measurementId: 'G-SFF602NMFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zsecRS9A8r1eqn49Ar6tRJWuhjhgZWY',
    appId: '1:649861279221:android:4ea3651cf5d510326f04bc',
    messagingSenderId: '649861279221',
    projectId: 'report-app-ccc12',
    storageBucket: 'report-app-ccc12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vUvwkRf0LHsMrW_Lw5FI7KmoVWM0kkk',
    appId: '1:649861279221:ios:24b2175f87153fa26f04bc',
    messagingSenderId: '649861279221',
    projectId: 'report-app-ccc12',
    storageBucket: 'report-app-ccc12.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3vUvwkRf0LHsMrW_Lw5FI7KmoVWM0kkk',
    appId: '1:649861279221:ios:24b2175f87153fa26f04bc',
    messagingSenderId: '649861279221',
    projectId: 'report-app-ccc12',
    storageBucket: 'report-app-ccc12.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcQXZpw7NqHhmXzYPuZdfjKoad44gJW0',
    appId: '1:649861279221:web:d2dbea53dbc02cb36f04bc',
    messagingSenderId: '649861279221',
    projectId: 'report-app-ccc12',
    authDomain: 'report-app-ccc12.firebaseapp.com',
    storageBucket: 'report-app-ccc12.firebasestorage.app',
    measurementId: 'G-FYRZDHK4WW',
  );
}