// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38DnSdbrlUPjt2c7jqMa57ng1lmTcMBU',
    appId: '1:223519695109:web:c7d66882fc2f4174a6576c',
    messagingSenderId: '223519695109',
    projectId: 'my-civic-app',
    authDomain: 'my-civic-app.firebaseapp.com',
    storageBucket: 'my-civic-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClv6I_is4XulQ2V351wcCeVd8RyY8S3Bw',
    appId: '1:223519695109:android:95a604e69ce18695a6576c',
    messagingSenderId: '223519695109',
    projectId: 'my-civic-app',
    storageBucket: 'my-civic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJXUMZhL7FFdftucfTGBs9JX-WYVtIBQ',
    appId: '1:223519695109:ios:d049faebc967b41aa6576c',
    messagingSenderId: '223519695109',
    projectId: 'my-civic-app',
    storageBucket: 'my-civic-app.firebasestorage.app',
    androidClientId:
        '223519695109-idf7dnioffvjcgd6037g9fn1e4voifb8.apps.googleusercontent.com',
    iosClientId:
        '223519695109-02l3lo247qg7k9kjq3570bafrc4dcpjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJXUMZhL7FFdftucfTGBs9JX-WYVtIBQ',
    appId: '1:223519695109:ios:d049faebc967b41aa6576c',
    messagingSenderId: '223519695109',
    projectId: 'my-civic-app',
    storageBucket: 'my-civic-app.firebasestorage.app',
    androidClientId:
        '223519695109-idf7dnioffvjcgd6037g9fn1e4voifb8.apps.googleusercontent.com',
    iosClientId:
        '223519695109-02l3lo247qg7k9kjq3570bafrc4dcpjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38DnSdbrlUPjt2c7jqMa57ng1lmTcMBU',
    appId: '1:223519695109:web:921d0b399ca1cda9a6576c',
    messagingSenderId: '223519695109',
    projectId: 'my-civic-app',
    authDomain: 'my-civic-app.firebaseapp.com',
    storageBucket: 'my-civic-app.firebasestorage.app',
  );
}
