// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGW0FVMF2gjDChPcbMbfdkY3zp9LaiISE',
    appId: '1:457064350295:web:cfdbac285c7fe1e533d912',
    messagingSenderId: '457064350295',
    projectId: 'my-civic-pro',
    authDomain: 'my-civic-pro.firebaseapp.com',
    storageBucket: 'my-civic-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanUIcn-pY9WzJE7YVkJvU683nGuqXU9A',
    appId: '1:457064350295:android:da333f1933d07b4233d912',
    messagingSenderId: '457064350295',
    projectId: 'my-civic-pro',
    storageBucket: 'my-civic-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrC7iTGHiJXAkBQLht6uhz5oqpd99PHs',
    appId: '1:457064350295:ios:874acaf7003a5d0533d912',
    messagingSenderId: '457064350295',
    projectId: 'my-civic-pro',
    storageBucket: 'my-civic-pro.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKrC7iTGHiJXAkBQLht6uhz5oqpd99PHs',
    appId: '1:457064350295:ios:874acaf7003a5d0533d912',
    messagingSenderId: '457064350295',
    projectId: 'my-civic-pro',
    storageBucket: 'my-civic-pro.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGW0FVMF2gjDChPcbMbfdkY3zp9LaiISE',
    appId: '1:457064350295:web:de5ee816b2fecf0133d912',
    messagingSenderId: '457064350295',
    projectId: 'my-civic-pro',
    authDomain: 'my-civic-pro.firebaseapp.com',
    storageBucket: 'my-civic-pro.firebasestorage.app',
  );
}
