import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'auth/login_page.dart';
import 'auth/signup_page.dart';
import 'pages/welcome_page.dart';
import 'pages/dashboard_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Civics Reporter',

      // Material 3 theme with color seed
      theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),

      // Use a StreamBuilder to check authentication state and determine the initial page
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Show a loading indicator while checking auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }

          // If the user is logged in, show the DashboardPage
          if (snapshot.hasData) {
            return const DashboardPage();
          }

          // Otherwise, show the WelcomePage
          return const WelcomePage();
        },
      ),

      // Named routes for navigation
      routes: {
        '/welcome': (context) => const WelcomePage(),
        '/login': (context) => const LoginPage(),
        '/signup': (context) => const SignupPage(),
        '/dashboard': (context) => const DashboardPage(),
      },

      // Optional: handle unknown routes gracefully
      onUnknownRoute: (settings) =>
          MaterialPageRoute(builder: (context) => const WelcomePage()),
    );
  }
}
